### ISSUE TITLE
useSourceAsTarget in XLIFF 2.0 does not work

### ISSUE THREAD

**Issue by martinroob** [martinroob/ngx-i18nsupport-lib#4]
useSourceAsTarget throws execption:
```
     TypeError: Cannot read property 'appendChild' of undefined
    at Xliff2TransUnit.useSourceAsTarget (S:\experimente\ngx-i18nsupport\node_modules\ngx-i18nsupport-lib\bundles\ngx-i18nsupport-lib.umd.js:3392:42)
    at Xliff2File.useSourceAsTarget (S:\experimente\ngx-i18nsupport\node_modules\ngx-i18nsupport-lib\bundles\ngx-i18nsupport-lib.umd.js:3128:19)
```

**Comment by martinroob** [comment]
fixed with 0.1.1
